name: project_creator
description: A sample command-line application.
version: 0.0.1

environment:
  sdk: '>=2.18.0 <3.0.0'

executables:
  project-creator: project_creator

dev_dependencies:
  lints: ^2.0.0
dependencies:
  cli_dialog: ^0.5.0
